# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_location', models.CharField(max_length=255)),
                ('last_password_modified_time', models.DateTimeField()),
                ('last_login_ip', models.CharField(max_length=255)),
                ('last_login_ip_location', models.CharField(max_length=255)),
                ('total_buy_sell_deposit_withdraw', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('national_id_proof', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=255)),
                ('user_fullname_as_in_bank', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('name_of_the_bank', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('swift_code', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=10)),
                ('icon_absolute_link', models.CharField(max_length=255)),
                ('icon_relative_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(verbose_name=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.CharField(max_length=255)),
                ('browser_info', models.CharField(max_length=255)),
                ('cookies', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
