# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=10)),
                ('icon_absolute_link', models.CharField(max_length=255)),
                ('icon_relative_link', models.CharField(max_length=255)),
            ],
        ),
    ]
